# Generated by Django 5.2.7 on 2025-10-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebasic',
            name='leadership_info',
            field=models.JSONField(blank=True, default=dict, help_text='Leadership-related information and permissions', verbose_name='leadership information'),
        ),
    ]
