# Generated by Django 5.2.7 on 2025-10-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofilebasic_leadership_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='photo_moderation_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='approved', max_length=20, verbose_name='moderation status'),
        ),
    ]
