# Generated by Django 5.2.7 on 2025-11-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_approve_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebasic',
            name='first_name',
            field=models.CharField(blank=True, help_text='Optional first name', max_length=30, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='userprofilebasic',
            name='last_name',
            field=models.CharField(blank=True, help_text='Optional last name', max_length=30, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='userprofilebasic',
            name='location',
            field=models.CharField(blank=True, help_text='User location (city, state, or general area)', max_length=255, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='userprofilebasic',
            name='post_code',
            field=models.CharField(blank=True, help_text='User post code (city, state, or general area)', max_length=255, verbose_name='post code'),
        ),
    ]
