# Generated by Django 5.2.7 on 2025-11-05 13:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofilebasic_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilebasic',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Geographic point for spatial queries (auto-populated from lat/lng)', null=True, srid=4326, verbose_name='coordinates'),
        ),
        migrations.AddField(
            model_name='userprofilebasic',
            name='geocoded_address',
            field=models.CharField(blank=True, help_text='Full address returned from geocoding service', max_length=500, verbose_name='geocoded address'),
        ),
        migrations.AddField(
            model_name='userprofilebasic',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, help_text='When the address was last geocoded', null=True, verbose_name='geocoded at'),
        ),
        migrations.AddField(
            model_name='userprofilebasic',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for location-based search', max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='userprofilebasic',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for location-based search', max_digits=9, null=True, verbose_name='longitude'),
        ),
    ]
