# Generated by Django 5.2.7 on 2025-11-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_add_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='photo',
            field=models.TextField(blank=True, help_text='Profile photo stored as Base64 data URL (max 5MB)', null=True),
        ),
        migrations.AlterField(
            model_name='profilephoto',
            name='thumbnail',
            field=models.TextField(blank=True, help_text='Thumbnail stored as Base64 data URL (150x150)', null=True),
        ),
    ]
