# Generated by Django 5.2.7 on 2025-10-29 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique identifier for this setting', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Setting value (will be parsed according to setting_type)')),
                ('setting_type', models.CharField(choices=[('boolean', 'Boolean (True/False)'), ('integer', 'Integer Number'), ('float', 'Decimal Number'), ('string', 'Text String'), ('json', 'JSON Object')], default='string', max_length=20)),
                ('category', models.CharField(choices=[('throttling', '🔒 Throttling & Rate Limiting'), ('security', '🛡️ Security Features'), ('development', '🔧 Development Tools'), ('email', '📧 Email Configuration'), ('logging', '📊 Logging & Monitoring')], default='development', max_length=50)),
                ('description', models.TextField(help_text='Description of what this setting controls')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this setting is currently active')),
                ('environment_restriction', models.CharField(choices=[('any', 'Any Environment'), ('development', 'Development Only'), ('staging', 'Staging Only'), ('testing', 'Testing Only'), ('production', 'Production Only')], default='development', help_text='Which environments this setting can be used in', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['category', 'key'],
            },
        ),
    ]
