# Generated by Django 5.2.7 on 2025-11-01 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the group was archived (soft delete)', null=True, verbose_name='archived at'),
        ),
        migrations.AddField(
            model_name='group',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_groups', to=settings.AUTH_USER_MODEL, verbose_name='archived by'),
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who originally created this group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_by'], name='group_group_created_e50987_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['archived_at'], name='group_group_archive_6ce28e_idx'),
        ),
    ]
