# Generated by Django 5.2.7 on 2025-11-01 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_add_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_groups', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
    ]
