# Generated by Django 5.2.7 on 2025-11-05 12:10

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_add_last_updated_by'),
    ]

    operations = [
        # Enable PostGIS extension for geographic queries
        CreateExtension('postgis'),
    ]
