# Generated by Django 5.2.7 on 2025-11-05 12:10

from django.db import migrations


def enable_postgis(apps, schema_editor):
    """
    Enable PostGIS extension if available.
    Gracefully skips if PostGIS is not installed on the database server.
    """
    try:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("CREATE EXTENSION IF NOT EXISTS postgis")
        print("✅ PostGIS extension enabled successfully")
    except Exception as e:
        # PostGIS not available - log warning but don't fail migration
        print(f"⚠️  PostGIS extension not available: {e}")
        print("⚠️  Location-based features will be limited without PostGIS")
        print("ℹ️  To enable PostGIS: Install postgresql-XX-postgis on your database server")


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_add_last_updated_by'),
    ]

    operations = [
        migrations.RunPython(enable_postgis, reverse_code=migrations.RunPython.noop),
    ]
