# Generated by Django 5.2.7 on 2025-11-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_add_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='photo',
            field=models.TextField(blank=True, help_text='Group photo or banner image (Base64 encoded)', null=True, verbose_name='group photo'),
        ),
    ]
