# Generated by Django 5.2.7 on 2025-11-06 09:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0005_add_location_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Discussion title (5-200 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('content', models.TextField(help_text='Discussion content (min 10 characters)', validators=[django.core.validators.MinLengthValidator(10)])),
                ('category', models.CharField(choices=[('bible_study', 'Bible Study'), ('prayer_worship', 'Prayer & Worship'), ('faith_discipleship', 'Faith & Discipleship'), ('testimonies', 'Testimonies'), ('general', 'General Discussion')], default='general', help_text='Discussion category', max_length=20)),
                ('comment_count', models.PositiveIntegerField(default=0, help_text='Number of comments (updated via signals)')),
                ('reaction_count', models.PositiveIntegerField(default=0, help_text='Number of reactions (updated via signals)')),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned discussions appear at the top of the feed')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(help_text='User who created this discussion', on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='The group this discussion belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='group.group')),
            ],
            options={
                'db_table': 'messaging_discussion',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Comment content', validators=[django.core.validators.MinLengthValidator(1)])),
                ('reaction_count', models.PositiveIntegerField(default=0, help_text='Number of reactions')),
                ('is_edited', models.BooleanField(default=False, help_text='Whether this comment has been edited')),
                ('edited_at', models.DateTimeField(blank=True, help_text='Last edit timestamp', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(help_text='User who wrote this comment', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for threaded replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messaging.comment')),
                ('discussion', models.ForeignKey(help_text='Discussion this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='messaging.discussion')),
            ],
            options={
                'db_table': 'messaging_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('discussion', 'Discussion'), ('prayer', 'Prayer Request'), ('testimony', 'Testimony'), ('scripture', 'Scripture')], help_text='Type of content', max_length=20)),
                ('content_id', models.UUIDField(help_text='ID of the actual content object')),
                ('title', models.CharField(help_text='Content title/preview', max_length=500)),
                ('preview', models.TextField(help_text='Content preview (first 300 chars)', max_length=300)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('reaction_count', models.PositiveIntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(help_text='When the content was created')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Author of the content', on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Group this feed item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='group.group')),
            ],
            options={
                'db_table': 'messaging_feed_item',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('new_discussion', 'New Discussion'), ('new_comment', 'New Comment'), ('new_reaction', 'New Reaction'), ('urgent_prayer', 'Urgent Prayer'), ('prayer_answered', 'Prayer Answered')], help_text='Type of notification', max_length=30)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('skipped_quiet_hours', 'Skipped - Quiet Hours'), ('skipped_rate_limit', 'Skipped - Rate Limit'), ('skipped_disabled', 'Skipped - Disabled')], help_text='Notification status', max_length=30)),
                ('to_email', models.EmailField(help_text='Email address notification was sent to', max_length=254)),
                ('subject', models.CharField(help_text='Email subject line', max_length=200)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who received (or should have received) notification', on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_notification_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_enabled', models.BooleanField(default=True, help_text='Master switch for all email notifications')),
                ('email_new_discussion', models.BooleanField(default=True, help_text='Email when new discussion is posted')),
                ('email_new_comment', models.BooleanField(default=True, help_text='Email when someone comments on your post')),
                ('email_new_reaction', models.BooleanField(default=False, help_text='Email when someone reacts to your content')),
                ('email_urgent_prayer', models.BooleanField(default=True, help_text='Email for urgent prayer requests')),
                ('quiet_hours_enabled', models.BooleanField(default=True, help_text='Enable quiet hours (no emails during this time)')),
                ('quiet_hours_start', models.TimeField(default='22:00', help_text='Quiet hours start time (default: 10 PM)')),
                ('quiet_hours_end', models.TimeField(default='08:00', help_text='Quiet hours end time (default: 8 AM)')),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, help_text='Token for one-click unsubscribe links', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_notification_preference',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('👍', 'Thumbs Up'), ('❤️', 'Heart'), ('🙏', 'Praying'), ('🔥', 'Fire'), ('👏', 'Clapping'), ('😊', 'Smile'), ('💯', '100')], default='👍', help_text='Type of reaction', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, help_text='Comment being reacted to (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.comment')),
                ('discussion', models.ForeignKey(blank=True, help_text='Discussion being reacted to (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='messaging.discussion')),
                ('user', models.ForeignKey(help_text='User who reacted', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_reaction',
            },
        ),
        migrations.CreateModel(
            name='CommentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Comment content before edit')),
                ('edited_at', models.DateTimeField(auto_now_add=True, help_text='When this edit was made')),
                ('comment', models.ForeignKey(help_text='Comment that was edited', on_delete=django.db.models.deletion.CASCADE, related_name='edit_history', to='messaging.comment')),
                ('edited_by', models.ForeignKey(help_text='User who made the edit', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comment histories',
                'db_table': 'messaging_comment_history',
                'ordering': ['-edited_at'],
                'indexes': [models.Index(fields=['comment', '-edited_at'], name='messaging_c_comment_68feb2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['group', '-created_at'], name='messaging_d_group_i_b244d0_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['group', 'is_deleted', '-created_at'], name='messaging_d_group_i_d98f19_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['author', '-created_at'], name='messaging_d_author__7164b5_idx'),
        ),
        migrations.AddIndex(
            model_name='discussion',
            index=models.Index(fields=['category', '-created_at'], name='messaging_d_categor_2959ec_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['discussion', '-created_at'], name='messaging_c_discuss_efb8db_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['discussion', 'is_deleted', '-created_at'], name='messaging_c_discuss_2ddb98_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-created_at'], name='messaging_c_author__604139_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', '-created_at'], name='messaging_c_parent__b262a0_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['group', 'is_deleted', '-created_at'], name='messaging_f_group_i_401e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['group', 'content_type', '-created_at'], name='messaging_f_group_i_19c98f_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['author', '-created_at'], name='messaging_f_author__b066c4_idx'),
        ),
        migrations.AddIndex(
            model_name='feeditem',
            index=models.Index(fields=['content_type', 'content_id'], name='messaging_f_content_8b133d_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', '-created_at'], name='messaging_n_user_id_91e72e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification_type', '-created_at'], name='messaging_n_notific_38ce20_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status', '-created_at'], name='messaging_n_status_c20418_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['discussion', 'reaction_type'], name='messaging_r_discuss_ef1bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['comment', 'reaction_type'], name='messaging_r_comment_b611e5_idx'),
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=['user', '-created_at'], name='messaging_r_user_id_c5fb79_idx'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('discussion__isnull', False)), fields=('user', 'discussion'), name='unique_user_discussion_reaction'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('user', 'comment'), name='unique_user_comment_reaction'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('discussion__isnull', False)), models.Q(('comment__isnull', False), ('discussion__isnull', True)), _connector='OR'), name='reaction_for_discussion_or_comment'),
        ),
    ]
