# Generated by Django 5.2.7 on 2025-11-06 11:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reported',
            field=models.BooleanField(default=False, help_text='True if content has been reported'),
        ),
        migrations.AddField(
            model_name='comment',
            name='report_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of active reports'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='is_reported',
            field=models.BooleanField(default=False, help_text='True if content has been reported'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='report_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of active reports'),
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(help_text='ID of the reported content')),
                ('reason', models.CharField(choices=[('spam', 'Spam or advertising'), ('inappropriate', 'Inappropriate content'), ('harassment', 'Harassment or bullying'), ('off_topic', 'Off-topic or not faith-related'), ('false_info', 'False or misleading information'), ('other', 'Other (see details)')], help_text='Reason for reporting', max_length=20)),
                ('details', models.TextField(blank=True, help_text='Additional details about the report', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('reviewing', 'Under review'), ('resolved', 'Resolved (action taken)'), ('dismissed', 'Dismissed (no action needed)')], default='pending', help_text='Current status of the report', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the report was reviewed', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the reviewer', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(help_text='Type of content being reported', limit_choices_to={'model__in': ['discussion', 'comment']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(help_text='User who reported the content', on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Group leader who reviewed this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messaging_content_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='messaging_c_status_2d5010_idx'), models.Index(fields=['content_type', 'object_id'], name='messaging_c_content_79394d_idx'), models.Index(fields=['reporter', '-created_at'], name='messaging_c_reporte_49f833_idx'), models.Index(fields=['reviewed_by', '-created_at'], name='messaging_c_reviewe_3b91b3_idx')],
                'constraints': [models.UniqueConstraint(fields=('reporter', 'content_type', 'object_id'), name='unique_report_per_user_per_content')],
            },
        ),
    ]
