# Generated by Django 5.2.7 on 2025-11-06 11:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_add_location_fields'),
        ('messaging', '0002_comment_is_reported_comment_report_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Brief prayer request title', max_length=200)),
                ('content', models.TextField(help_text='Detailed prayer request (max 1000 characters)', max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('category', models.CharField(choices=[('personal', 'Personal'), ('family', 'Family'), ('community', 'Community'), ('thanksgiving', 'Thanksgiving/Praise')], default='personal', help_text='Category of prayer request', max_length=20)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent')], default='normal', help_text='Urgency level', max_length=10)),
                ('is_answered', models.BooleanField(default=False, help_text='Whether this prayer has been answered')),
                ('answered_at', models.DateTimeField(blank=True, help_text='When the prayer was answered', null=True)),
                ('answer_description', models.TextField(blank=True, help_text='Description of how prayer was answered', max_length=1000)),
                ('prayer_count', models.PositiveIntegerField(default=0, help_text='Number of people praying')),
                ('comment_count', models.PositiveIntegerField(default=0, help_text='Number of comments')),
                ('is_reported', models.BooleanField(default=False, help_text='True if content has been reported')),
                ('report_count', models.PositiveIntegerField(default=0, help_text='Number of active reports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who created this prayer request', on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Group this prayer request belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to='group.group')),
            ],
            options={
                'db_table': 'messaging_prayer_request',
                'ordering': ['-urgency', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scripture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(help_text='Bible reference (e.g., "John 3:16", "Psalm 23:1-6")', max_length=100)),
                ('verse_text', models.TextField(help_text='Full scripture text')),
                ('translation', models.CharField(default='KJV', help_text='Bible translation (KJV, NIV, ESV, etc.)', max_length=20)),
                ('personal_reflection', models.TextField(blank=True, help_text='Personal thoughts and application', max_length=1000)),
                ('source', models.CharField(choices=[('api', 'Bible API'), ('manual', 'Manual Entry')], default='api', help_text='How the verse was added', max_length=10)),
                ('reaction_count', models.PositiveIntegerField(default=0, help_text='Number of reactions')),
                ('comment_count', models.PositiveIntegerField(default=0, help_text='Number of comments')),
                ('is_reported', models.BooleanField(default=False, help_text='True if content has been reported')),
                ('report_count', models.PositiveIntegerField(default=0, help_text='Number of active reports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User who shared this scripture', on_delete=django.db.models.deletion.CASCADE, related_name='scriptures', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Group this scripture share belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='scriptures', to='group.group')),
            ],
            options={
                'db_table': 'messaging_scripture',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Testimony title', max_length=200)),
                ('content', models.TextField(help_text='Full testimony (max 2000 characters)', max_length=2000, validators=[django.core.validators.MinLengthValidator(20)])),
                ('is_public', models.BooleanField(default=False, help_text='Share publicly to inspire others')),
                ('public_shared_at', models.DateTimeField(blank=True, help_text='When testimony was shared publicly', null=True)),
                ('is_public_approved', models.BooleanField(default=False, help_text='Leader approval for public sharing')),
                ('reaction_count', models.PositiveIntegerField(default=0, help_text='Number of reactions')),
                ('comment_count', models.PositiveIntegerField(default=0, help_text='Number of comments')),
                ('is_reported', models.BooleanField(default=False, help_text='True if content has been reported')),
                ('report_count', models.PositiveIntegerField(default=0, help_text='Number of active reports')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_prayer', models.ForeignKey(blank=True, help_text='Link to answered prayer request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonies', to='messaging.prayerrequest')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Leader who approved public sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_testimonies', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(help_text='User who shared this testimony', on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Group this testimony belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='group.group')),
            ],
            options={
                'verbose_name_plural': 'testimonies',
                'db_table': 'messaging_testimony',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['group', '-created_at'], name='messaging_p_group_i_1fc597_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['group', 'urgency', '-created_at'], name='messaging_p_group_i_0f3646_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['author', '-created_at'], name='messaging_p_author__2d3190_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['category', '-created_at'], name='messaging_p_categor_519a56_idx'),
        ),
        migrations.AddIndex(
            model_name='prayerrequest',
            index=models.Index(fields=['is_answered', '-created_at'], name='messaging_p_is_answ_59b8ea_idx'),
        ),
        migrations.AddIndex(
            model_name='scripture',
            index=models.Index(fields=['group', '-created_at'], name='messaging_s_group_i_5ebbb4_idx'),
        ),
        migrations.AddIndex(
            model_name='scripture',
            index=models.Index(fields=['author', '-created_at'], name='messaging_s_author__18b10f_idx'),
        ),
        migrations.AddIndex(
            model_name='scripture',
            index=models.Index(fields=['reference'], name='messaging_s_referen_022c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='scripture',
            index=models.Index(fields=['translation', '-created_at'], name='messaging_s_transla_5fd3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='testimony',
            index=models.Index(fields=['group', '-created_at'], name='messaging_t_group_i_0b6903_idx'),
        ),
        migrations.AddIndex(
            model_name='testimony',
            index=models.Index(fields=['author', '-created_at'], name='messaging_t_author__23b2de_idx'),
        ),
        migrations.AddIndex(
            model_name='testimony',
            index=models.Index(fields=['is_public', 'is_public_approved', '-created_at'], name='messaging_t_is_publ_32feb4_idx'),
        ),
        migrations.AddIndex(
            model_name='testimony',
            index=models.Index(fields=['answered_prayer', '-created_at'], name='messaging_t_answere_15a654_idx'),
        ),
    ]
