# Generated by Django 5.2.7 on 2025-11-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_prayerrequest_scripture_testimony_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='email_new_prayer',
            field=models.BooleanField(default=True, help_text='Email for new prayer requests in your groups'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_prayer_answered',
            field=models.BooleanField(default=True, help_text='Email when a prayer you prayed for is answered'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_scripture_shared',
            field=models.BooleanField(default=False, help_text='Email when scripture is shared in your groups'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_testimony_approved',
            field=models.BooleanField(default=True, help_text='Email when your testimony is approved for public sharing'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='email_testimony_shared',
            field=models.BooleanField(default=True, help_text='Email when new testimonies are shared'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('new_discussion', 'New Discussion'), ('new_comment', 'New Comment'), ('new_reaction', 'New Reaction'), ('discussion_pinned', 'Discussion Pinned'), ('urgent_prayer', 'Urgent Prayer Request'), ('prayer_answered', 'Prayer Answered'), ('new_prayer', 'New Prayer Request'), ('testimony_shared', 'New Testimony'), ('testimony_approved', 'Testimony Approved for Public'), ('scripture_shared', 'New Scripture')], help_text='Type of notification', max_length=30),
        ),
    ]
