# Generated by Django 5.2.7 on 2025-11-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_notificationpreference_email_new_prayer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the content was created'),
        ),
    ]
