# Generated by Django 5.2.7 on 2025-11-08 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('messaging', '0006_feeditemview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_id',
            field=models.UUIDField(blank=True, help_text='ID of the content being commented on', null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Type of content being commented on', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(blank=True, help_text='Discussion this comment belongs to (deprecated - use content_type/content_id)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='messaging.discussion'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'content_id', '-created_at'], name='messaging_c_content_8ff536_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'content_id', 'is_deleted', '-created_at'], name='messaging_c_content_3b622a_idx'),
        ),
    ]
