# Generated by Django 5.2.7 on 2025-11-08 11:02

from django.db import migrations


def backfill_comment_content_types(apps, schema_editor):
    """
    Backfill content_type and content_id for existing comments.
    All existing comments are linked to discussions, so we set:
    - content_type = Discussion ContentType
    - content_id = discussion.id
    """
    Comment = apps.get_model('messaging', 'Comment')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Discussion = apps.get_model('messaging', 'Discussion')
    
    # Get the ContentType for Discussion
    discussion_content_type = ContentType.objects.get_for_model(Discussion)
    
    # Update all comments that have a discussion
    comments_to_update = Comment.objects.filter(discussion__isnull=False)
    
    for comment in comments_to_update:
        comment.content_type = discussion_content_type
        comment.content_id = comment.discussion_id
        comment.save(update_fields=['content_type', 'content_id'])
    
    print(f"✅ Backfilled {comments_to_update.count()} comments with content_type and content_id")


def reverse_backfill(apps, schema_editor):
    """
    Reverse migration - clear content_type and content_id.
    """
    Comment = apps.get_model('messaging', 'Comment')
    Comment.objects.all().update(content_type=None, content_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_add_polymorphic_comments'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(backfill_comment_content_types, reverse_backfill),
    ]
