# Generated by Django 5.2.7 on 2025-11-08 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_reactions_to_generic_fk(apps, schema_editor):
    """
    Migrate existing reactions from legacy ForeignKeys to GenericForeignKey.

    This populates content_type and object_id from discussion/comment fields.
    """
    Reaction = apps.get_model('messaging', 'Reaction')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get ContentType instances
    try:
        discussion_ct = ContentType.objects.get(
            app_label='messaging', model='discussion')
        comment_ct = ContentType.objects.get(
            app_label='messaging', model='comment')
    except ContentType.DoesNotExist:
        # If ContentTypes don't exist yet, skip migration
        return

    # Migrate reactions on discussions
    discussion_reactions = Reaction.objects.filter(discussion__isnull=False)
    for reaction in discussion_reactions:
        reaction.content_type = discussion_ct
        reaction.object_id = reaction.discussion_id
        reaction.save(update_fields=['content_type', 'object_id'])

    # Migrate reactions on comments
    comment_reactions = Reaction.objects.filter(comment__isnull=False)
    for reaction in comment_reactions:
        reaction.content_type = comment_ct
        reaction.object_id = reaction.comment_id
        reaction.save(update_fields=['content_type', 'object_id'])


def reverse_migrate_reactions(apps, schema_editor):
    """
    Reverse migration: populate legacy fields from GenericForeignKey.
    """
    Reaction = apps.get_model('messaging', 'Reaction')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    try:
        discussion_ct = ContentType.objects.get(
            app_label='messaging', model='discussion')
        comment_ct = ContentType.objects.get(
            app_label='messaging', model='comment')
    except ContentType.DoesNotExist:
        return

    # Restore discussion reactions
    Reaction.objects.filter(content_type=discussion_ct).update(
        discussion_id=models.F('object_id')
    )

    # Restore comment reactions
    Reaction.objects.filter(content_type=comment_ct).update(
        comment_id=models.F('object_id')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('messaging', '0008_backfill_comment_content_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reaction',
            name='unique_user_discussion_reaction',
        ),
        migrations.RemoveConstraint(
            model_name='reaction',
            name='unique_user_comment_reaction',
        ),
        migrations.RemoveConstraint(
            model_name='reaction',
            name='reaction_for_discussion_or_comment',
        ),
        migrations.RemoveIndex(
            model_name='reaction',
            name='messaging_r_discuss_ef1bdf_idx',
        ),
        migrations.RemoveIndex(
            model_name='reaction',
            name='messaging_r_comment_b611e5_idx',
        ),
        migrations.AddField(
            model_name='reaction',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Type of content being reacted to', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='object_id',
            field=models.UUIDField(
                blank=True, help_text='ID of the content being reacted to', null=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='comment',
            field=models.ForeignKey(blank=True, help_text='[DEPRECATED] Use content_type/object_id instead', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='reactions_legacy', to='messaging.comment'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='discussion',
            field=models.ForeignKey(blank=True, help_text='[DEPRECATED] Use content_type/object_id instead', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, related_name='reactions_legacy', to='messaging.discussion'),
        ),
        # Data migration: populate GenericForeignKey fields from legacy fields
        migrations.RunPython(
            migrate_reactions_to_generic_fk,
            reverse_migrate_reactions
        ),
        migrations.AddIndex(
            model_name='reaction',
            index=models.Index(fields=[
                               'content_type', 'object_id', 'reaction_type'], name='messaging_r_content_b1b39c_idx'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(fields=(
                'user', 'content_type', 'object_id'), name='unique_user_content_reaction'),
        ),
    ]
