# Generated by Django 5.2.7 on 2025-11-09 19:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_change_photo_to_base64'),
        ('messaging', '0009_add_genericforeignkey_to_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerrequest',
            name='urgency',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', help_text='Urgency level', max_length=10),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_type', models.CharField(choices=[('group_inquiry', 'Group Inquiry'), ('direct_message', 'Direct Message')], default='group_inquiry', help_text='Type of conversation context', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='active', help_text='Current status of the conversation', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the conversation was closed', null=True)),
                ('close_reason', models.CharField(blank=True, choices=[('joined_group', 'Joined Group'), ('not_interested', 'Not Interested'), ('resolved', 'Resolved'), ('other', 'Other')], help_text='Reason for closing the conversation', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the conversation was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the conversation was last updated')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='When the last message was sent', null=True)),
                ('closed_by', models.ForeignKey(blank=True, help_text='User who closed the conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_conversations', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text='Group related to this conversation (for group inquiries)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_conversations', to='group.group')),
                ('participants', models.ManyToManyField(help_text='Users participating in this conversation', related_name='private_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Message content', validators=[django.core.validators.MinLengthValidator(1)])),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read by recipient')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the message was sent')),
                ('conversation', models.ForeignKey(help_text='Conversation this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='private_messages', to='messaging.conversation')),
                ('sender', models.ForeignKey(help_text='User who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_private_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='messaging_c_last_me_3f31f1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status'], name='messaging_c_status_d014e4_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['context_type'], name='messaging_c_context_70f227_idx'),
        ),
        migrations.AddIndex(
            model_name='privatemessage',
            index=models.Index(fields=['conversation', 'created_at'], name='messaging_p_convers_fa2a23_idx'),
        ),
        migrations.AddIndex(
            model_name='privatemessage',
            index=models.Index(fields=['is_read'], name='messaging_p_is_read_1f00a1_idx'),
        ),
    ]
