# Generated by Django 5.2.7 on 2025-10-31 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ministry_experience_years', models.PositiveIntegerField(blank=True, help_text='Optional: Years of ministry or leadership experience', null=True, verbose_name='years of ministry experience')),
                ('previous_leadership_roles', models.TextField(blank=True, help_text='Optional: Previous leadership experience description', verbose_name='previous leadership roles')),
                ('ministry_interests', models.JSONField(blank=True, default=list, help_text="Areas of ministry interest (e.g., youth, couples, men's/women's groups)", verbose_name='ministry interests')),
                ('preferred_group_size', models.CharField(choices=[('small', '5-10 people'), ('medium', '10-20 people'), ('large', '20+ people')], default='small', max_length=20, verbose_name='preferred group size')),
                ('meeting_frequency_preference', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20, verbose_name='meeting frequency preference')),
                ('meeting_format_preference', models.JSONField(blank=True, default=list, help_text='Preferred formats: in_person, online, hybrid', verbose_name='meeting format preferences')),
                ('leadership_topics', models.JSONField(blank=True, default=list, help_text='Topic areas comfortable leading (e.g., prayer, bible_study, outreach)', verbose_name='leadership topics')),
                ('general_availability', models.JSONField(blank=True, default=dict, help_text='General availability by day/time (e.g., {"monday": ["evening"], "tuesday": ["morning", "evening"]})', verbose_name='general availability')),
                ('max_group_capacity', models.PositiveIntegerField(default=1, help_text='Maximum number of groups willing to lead simultaneously', verbose_name='maximum group capacity')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the leader is currently active', verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leadership_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leadership Profile',
                'verbose_name_plural': 'Leadership Profiles',
                'db_table': 'onboarding_leadership_profile',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='onboarding__user_id_424078_idx'), models.Index(fields=['is_active'], name='onboarding__is_acti_6a0b22_idx'), models.Index(fields=['created_at'], name='onboarding__created_0e14be_idx')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(help_text='The onboarding step this feedback relates to', max_length=50, verbose_name='step name')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 stars'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], help_text='1-5 star rating for this step', verbose_name='rating')),
                ('feedback_text', models.TextField(blank=True, help_text='Optional detailed feedback', verbose_name='feedback text')),
                ('was_confusing', models.BooleanField(default=False, verbose_name='was confusing')),
                ('was_helpful', models.BooleanField(default=True, verbose_name='was helpful')),
                ('suggestions', models.TextField(blank=True, help_text='Suggestions for improvement', verbose_name='suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Feedback',
                'verbose_name_plural': 'Onboarding Feedback',
                'db_table': 'onboarding_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='onboarding__user_id_c11a6c_idx'), models.Index(fields=['step_name'], name='onboarding__step_na_a04c1e_idx'), models.Index(fields=['rating'], name='onboarding__rating_a63eb7_idx')],
                'unique_together': {('user', 'step_name')},
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps_completed', models.JSONField(default=dict, help_text='Dictionary tracking completion timestamp for each step', verbose_name='completed steps')),
                ('total_steps', models.PositiveIntegerField(default=0, help_text="Total number of steps in user's personalized flow", verbose_name='total steps')),
                ('completion_percentage', models.FloatField(default=0.0, help_text='Percentage of onboarding completed', verbose_name='completion percentage')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='onboarding started at')),
                ('last_activity_at', models.DateTimeField(auto_now=True, verbose_name='last activity at')),
                ('time_spent_minutes', models.PositiveIntegerField(default=0, help_text='Total time spent in onboarding process', verbose_name='time spent (minutes)')),
                ('dropped_off_at_step', models.CharField(blank=True, help_text='Step where user last stopped (for drop-off analysis)', max_length=50, null=True, verbose_name='dropped off at step')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Progress',
                'verbose_name_plural': 'Onboarding Progress Records',
                'db_table': 'onboarding_progress',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user'], name='onboarding__user_id_7bb12f_idx'), models.Index(fields=['completion_percentage'], name='onboarding__complet_0e6c26_idx'), models.Index(fields=['started_at'], name='onboarding__started_6ac78e_idx')],
            },
        ),
    ]
